# Setup
title:               Not By A Blogger
tagline:             'A simple Blog'
description:         'A blog for ones that can be interested by the life of Nunwan'
url:                 https://blog.nunwan.fr
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nunwan
  url:               https://Rob1B.github.io
  email:             perso@nunwan.fr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
