# Setup
title:               Nunwan's room
tagline:             'A little tour'
description:         'A blog for ones that can be interested in the life of Nunwan'
url:                 https://nunwan.fr
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nunwan
  url:               https://nunwan.fr
  email:             perso@nunwan.fr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
